sudo: required
services:
    - docker

before_install:
    - docker image build -t j127/docker-react -f Dockerfile.dev .

script:
    - docker container run -e CI=true j127/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "docker-react"
    environment: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-1-794111341249"
    bucket_path: "docker-react"
    on:
        branch: master
    access-key-id: $AWS_ACCESS_KEY
    secret-access-key:
        secure: "$AWS_SECRET_KEY"
